import type { Metadata } from "next";
import { 
  Oswald,
  Montserrat,
  Playfair_Display,
  Great_Vibes
} from "next/font/google"; 
import "./globals.css";
import {ConditionalFooter, ConditionalNavbar } from "@/components/general-components/ConditionalFooterAndHeader";
import { ProductProvider } from "@/contexts/ProductContext";
import { Toaster } from "@/components/ui/sonner";
import { GoogleAnalyticsTracker } from "@/components/analytics/GoogleAnalyticsTracker";

const oswald = Oswald({
  subsets: ["latin"],
  variable: "--font-oswald"
});

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat"
});

const playfairDisplay = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair-display"
})

const greatVibes = Great_Vibes({
  subsets: ["latin"],
  variable: "--font-great-vibes",
  weight: "400"
})

export const metadata: Metadata = {
  title: "Dolly's Closet ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
            ${oswald.variable} 
            ${montserrat.variable} 
            ${playfairDisplay.variable} 
            ${greatVibes.variable} 
            antialiased`
          }>

        <ProductProvider>
          <GoogleAnalyticsTracker />
          <ConditionalNavbar />
          {children}
          <ConditionalFooter />
          <Toaster duration={3000} />
        </ProductProvider>
      </body>
    </html>
  );
}
